---
- import_tasks: config-host.yml

- import_tasks: config.yml

- import_tasks: check-containers.yml

- name: Flush Handlers
  meta: flush_handlers

- import_tasks: podman-systemd.yml
  when:
    - kolla_container_engine == 'podman'
    - enable_openvswitch | bool
    - openvswitch_services['openvswitch-db-server'].host_in_groups | bool

- import_tasks: post-config.yml
