---
- name: Generate Podman systemd units for Open vSwitch
  include_role:
    name: common
    tasks_from: podman_systemd
  vars:
    service: "{{ ovs_service_item.value }}"
    service_name: "{{ ovs_service_item.key }}"
  loop: "{{ openvswitch_services | select_services_enabled_and_mapped_to_host | dict2items }}"
  loop_control:
    loop_var: ovs_service_item
    label: "{{ ovs_service_item.key }}"
